version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: dockerfile
    image: backend
    ports: 
      - 5000:5000
    command: npm start

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - /home/ubuntu/basilfarm-frontend/.next:/usr/share/nginx/html/
      - ./nginx/fullchain.pem:/etc/nginx/pem/
      - ./nginx/privkey.pem:/etc/nginx/pem/